### ISSUE TITLE
Error with MythicMobs

### ISSUE THREAD

**Issue by Xitryne** [Winds-Studio/DeathMessages#134]
![image](https://github.com/user-attachments/assets/eb5371c8-6006-4913-80d4-5309775ef960)

**Comment by Dreeam-qwq** [comment]
You should use dev build https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

And also please provide your DeathMessages config, using https://mclo.gs/

**Comment by Xitryne** [comment]
Settings.yml: https://api.mclo.gs/1/raw/nRPDRDc

**Comment by Dreeam-qwq** [comment]
> Settings.yml: https://api.mclo.gs/1/raw/nRPDRDc

EntityDeathMessages.yml as well

**Comment by Xitryne** [comment]
My EntityDeathMessages.yml as empty ^^

```
# Vanilla Entities
Entities: []

# Mythic-Mob Entities https://mythiccraft.io/index.php?resources/mythicmobs.1/
Mythic-Mobs-Entities: []
```

**Comment by Dreeam-qwq** [comment]
> My EntityDeathMessages.yml as empty ^^
> 
> ```
> # Vanilla Entities
> Entities: []
> 
> # Mythic-Mob Entities https://mythiccraft.io/index.php?resources/mythicmobs.1/
> Mythic-Mobs-Entities: []
> ```

Just to make sure you have right config

Can you try this build? https://github.com/Winds-Studio/DeathMessages/actions/runs/11214120459

**Comment by Xitryne** [comment]
```
ERROR13:47:21
Could not pass event MythicMobDeathEvent to DeathMessages v1.4.20-SNAPSHOT
Console13:47:21
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
	at dev.mrshawn.deathmessages.listeners.mythicmobs.MobDeath.onMythicMobDeath(MobDeath.java:32) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor513.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:454) ~[MythicMobs-5.7.2.jar:?]
	at io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144) ~[MythicMobs-5.7.2.jar:?]
	at io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131) ~[MythicMobs-5.7.2.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:166) ~[WildStacker-2024.3.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
13:47:47
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:166) ~[WildStacker-2024.3.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Xitryne** [comment]
I tried with the wrong version, wait

**Comment by Xitryne** [comment]
I no longer have any errors with the version you sent me, but if I get killed by a MythicMobs mob, DeathMessages detects it as a player.

**Comment by Xitryne** [comment]
![image](https://github.com/user-attachments/assets/ce5b5479-8584-42cf-b588-2851fed84c96)

**Comment by Dreeam-qwq** [comment]
> ![image](https://private-user-images.githubusercontent.com/53669476/374157682-ce5b5479-8584-42cf-b588-2851fed84c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDQxOTAsIm5iZiI6MTcyODMwMzg5MCwicGF0aCI6Ii81MzY2OTQ3Ni8zNzQxNTc2ODItY2U1YjU0NzktODU4NC00MmNmLWI1ODgtMjg1MWZlZDg0Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEyMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTgxNjExMzE0NmQ1MjgyZTM0MGM1Mzk4NDRjOTUxMTU2MmIxY2ZlNWJkZTRhYjc0MTYzN2NhZjkzYmI3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f2eyY64WGZ6jwWtjdg-XZ2yrcFbCf0PdfO3y_4pLwg4)

Enable `Debug` in `Settings.yml`

**Comment by Xitryne** [comment]
```
WARN16:49:38
[DeathMessages]: node: [Mobs.irongolem.Solo.Melee]
[DeathMessages]: node2: [Mobs.player.Solo.Melee]
```

With debug enabled I get this pop in the console when my death message in Chat

**Comment by Dreeam-qwq** [comment]
> node2

So you need to check in your `PlayerDeathMessages.yml`, whether the node `Mobs.irongolem.Solo.Melee` exists, if not, it will redirect to player death messages with same death type, and iron golem is not a player, so %killer_display% won't work

**Comment by Xitryne** [comment]
The error appears when I kill an enemy from MythicMob

**Comment by Xitryne** [comment]
Because my EntityDeathMessages.yml is empty, I can't think of any other reason.

**Comment by Dreeam-qwq** [comment]
> ![image](https://private-user-images.githubusercontent.com/53669476/374157682-ce5b5479-8584-42cf-b588-2851fed84c96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMjE1MjQsIm5iZiI6MTcyODMyMTIyNCwicGF0aCI6Ii81MzY2OTQ3Ni8zNzQxNTc2ODItY2U1YjU0NzktODU4NC00MmNmLWI1ODgtMjg1MWZlZDg0Yzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDE3MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExODg5ZjU1ZDk0ZTNjNzhmYjY2Nzg2MzIxNmM1MTdmZGNmY2ZjZjJlMTliODc4ZTM0ZTQ1NDczODIyYTVhZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0efJLnSbfAzX7GGF07okiENFYdV0VdR5ojoLkd_iEyE)

idk what are you talking about, this issue you opened is solved. 

And this picture you provide is another issue, has no relationship with this one.

**Comment by Dreeam-qwq** [comment]
> Yes, the error for which I opened this post has been fixed, but it has created a new one that I didn't have before.

For your new one
```
So you need to check in your PlayerDeathMessages.yml, whether the node Mobs.irongolem.Solo.Melee exists, if not, it will redirect to player death messages with same death type, and iron golem is not a player, so %killer_display% won't work
```

Can you send your `PlayerDeathMessages.yml` to me if you dont mind, you can send them in my discord dm, `dreeam___`
