### ISSUE TITLE
NoSuchMethod kyori

### ISSUE THREAD

**Issue by ghost** [Winds-Studio/DeathMessages#142]
```[13:07:12 ERROR]: Could not load 'plugins/DeathMessages-1.4.20-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.ComponentBuilder net.kyori.adventure.text.TextComponent$Builder.appendNewline()'
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.ComponentBuilder net.kyori.adventure.text.TextComponent$Builder.appendNewline()'
        at dev.mrshawn.deathmessages.DeathMessages.<init>(DeathMessages.java:299) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.lang.Class.newInstance(Class.java:725) ~[?:?]```

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/2b98165b6db791b7f9f287bf926de0ead2fccfa8, please use latest build from Releases.
