### ISSUE TITLE
[error] Could not pass event PlayerMoveEvent to DeathMessages v1.4.18-SNAPSHOT

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#23]
error: https://pastes.dev/yhEVmPQ9Dc

Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at dev.mrshawn.deathmessages.api.PlayerManager.getPlayer(PlayerManager.java:189) ~[?:?]
        at dev.mrshawn.deathmessages.listeners.OnMove.onMove(OnMove.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        ... 15 more

**Comment by Dreeam-qwq** [comment]
Fixed in 4a49cb8f007663fd76bb9477603309f4dd6910c5

**Comment by Dreeam-qwq** [comment]
should be fixed, 748277f615773b32cfcb1d5d73397aca444b3fcb
