### ISSUE TITLE
 Could not pass event PlayerMoveEvent to DeathMessages v1.4.18-SNAPSHOT org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#27]
[19:21:00 ERROR]: Could not pass event PlayerMoveEvent to DeathMessages v1.4.18-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:511) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:726) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:885) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:806) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:689) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at dev.mrshawn.deathmessages.api.PlayerManager.getPlayer(PlayerManager.java:190) ~[?:?]
        at dev.mrshawn.deathmessages.listeners.OnMove.onMove(OnMove.java:23) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor64.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Reaper-"fff830c"]
        ... 15 more

**Comment by Dreeam-qwq** [comment]
duplicate with #23

**Comment by F3F5** [comment]
> duplicate with #23

i dont see today any of errors by deathmessages! win!!!
