### ISSUE TITLE
[1.12.2] Plugin Error

### ISSUE THREAD

**Issue by F3F5** [Winds-Studio/DeathMessages#36]
Could not load 'plugins/DeathMessages-1.4.18-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1620]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1620]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.12.2.jar:git-Paper-1620]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:318) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[patched_1.12.2.jar:git-Paper-1620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component

**Comment by Dreeam-qwq** [comment]
Can't reproduce, you need to download the newest version in
https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build
![](https://github.com/Winds-Studio/DeathMessages/assets/61569423/c0096dd7-6b18-41f4-8ef7-1460c7d9bd1d)

(If you build plugin by yourself, you need to use `DeathMessages-1.4.18-SNAPSHOT-all.jar` with bigger size which there is a "-all" in the end)

**Comment by F3F5** [comment]
yes yourself, i'll chack later

**Comment by F3F5** [comment]
confirmed fix with -all
