### ISSUE TITLE
`%deathmessages_killer_name%` error parsing

### ISSUE THREAD

**Issue by cupang-afk** [Winds-Studio/DeathMessages#48]
- me walk
- friend kill
- console goes brr

trying to parse manually, and here is the log
```log
> papi parse cupang_afk %deathmessages_killer_name%
[15:57:25 WARN]: Unexpected exception while parsing console command "papi parse cupang_afk %deathmessages_killer_name%"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:541) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getName()" because the return value of "dev.mrshawn.deathmessages.api.PlayerManager.getLastEntityDamager()" is null
        at dev.mrshawn.deathmessages.hooks.PlaceholderAPIExtension.lambda$onPlaceholderRequest$0(PlaceholderAPIExtension.java:112) ~[DeathMessages [Github] [1.4.18].jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at dev.mrshawn.deathmessages.hooks.PlaceholderAPIExtension.onPlaceholderRequest(PlaceholderAPIExtension.java:101) ~[DeathMessages [Github] [1.4.18].jar:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:117) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 9 mor
```

i use [ParseOther](https://api.extendedclip.com/expansions/parseother/) in the death message
```%parseother_{deathmessages_killer_name}_{shortcut_player_displayname_or}%```
the reason is i have custom formatted display name using [Shortcut](https://api.extendedclip.com/expansions/shortcut/)

i want to get the custom formatted display name of the killer using parseother papi

**Comment by cupang-afk** [comment]
possibly affect `%deathmessages_killer_display_name%` too

**Comment by cupang-afk** [comment]
> possibly affect `%deathmessages_killer_display_name%` too

yes
```log
> papi parse cupang_afk %deathmessages_killer_display_name%
[15:58:47 WARN]: Unexpected exception while parsing console command "papi parse cupang_afk %deathmessages_killer_display_name%"
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:541) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2150]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getCustomName()" because the return value of "dev.mrshawn.deathmessages.api.PlayerManager.getLastEntityDamager()" is null
        at dev.mrshawn.deathmessages.hooks.PlaceholderAPIExtension.lambda$onPlaceholderRequest$0(PlaceholderAPIExtension.java:114) ~[DeathMessages [Github] [1.4.18].jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at dev.mrshawn.deathmessages.hooks.PlaceholderAPIExtension.onPlaceholderRequest(PlaceholderAPIExtension.java:101) ~[DeathMessages [Github] [1.4.18].jar:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:117) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-[SpigotMC-2.11.5].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**Comment by Dreeam-qwq** [comment]
You need to provide error when you are killed by friend. Also, you definitely got an error using papi parse, since you are not got attacked by any entity, how it returns the killer name?

**Comment by cupang-afk** [comment]
> You need to provide error when you are killed by friend. Also, you definitely got an error using papi parse, since you are not got attacked by any entity, how it returns the killer name?

welp i just tested it again and for some reason it fixed, perhaps i have missconfiguration ? (cuz i had reset the config after the error)
or it causes by the parseother extension ? 


anyway, imma close this issue, sorry for bothering you
