### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Ergail** [Winds-Studio/DeathMessages#49]
When my server starts up (1.20.2 PaperSpigot) i have this error after a very long freeze :

`[06:50:42] [Server thread/INFO]: [DeathMessages] Loading server plugin DeathMessages v1.4.19-SNAPSHOT
[07:21:03] [Server thread/ERROR]: [DeathMessages] Error initializing plugin 'DeathMessages-1.4.19-SNAPSHOT.jar' in folder 'plugins' (Is it up to date?)
java.lang.StackOverflowError: null
	at java.util.LinkedList.add(LinkedList.java:342) ~[?:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:695) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValueComment.produce(ParserImpl.java:696) ~[snakeyaml-2.2.jar:?]`

**Comment by ArionOwO** [comment]
I'm experiencing the same issue as well, me personally i'm on 1.20.2 paper latest.

**Comment by Dreeam-qwq** [comment]
The temp solution is to reset Messages.yml.

And this issue will truly fixed after I'm done with config refactor.

**Comment by Dreeam-qwq** [comment]
Can you replicate it on latest dev build?
https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

**Comment by Dreeam-qwq** [comment]
Can't replicate in laest dev build, seems be fixed

**Comment by AGuyNamedJens** [comment]
> Can you replicate it on latest dev build? https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build

I'm on the latest dev build, happens rarely. Once per week or 3 it still has the same issue sadly..

**Comment by Dreeam-qwq** [comment]
> > Can you replicate it on latest dev build? https://github.com/Winds-Studio/DeathMessages/releases/tag/dev-build
> 
> I'm on the latest dev build, happens rarely. Once per week or 3 it still has the same issue sadly..

well

**Comment by AGuyNamedJens** [comment]
![image](https://github.com/user-attachments/assets/876b4e30-0f71-456f-901a-290ddcb5ad81)
size seems to increase every week..

**Comment by Dreeam-qwq** [comment]
> ![image](https://private-user-images.githubusercontent.com/34610614/365453015-876b4e30-0f71-456f-901a-290ddcb5ad81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDA1OTQsIm5iZiI6MTcyNTg0MDI5NCwicGF0aCI6Ii8zNDYxMDYxNC8zNjU0NTMwMTUtODc2YjRlMzAtMGY3MS00NTZmLTkwMWEtMjkwZGRjYjVhZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjQwMzU3MzgwZmIzODg0MzY4OWY0YTRmYWFjMjRmY2FlZGU1NmI2NTc5ZDAzMTE1ZDc5YmJiOWU1MmJiZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Q2mMPmrOyL2ri4K0A5blkrcxp-ecb0k-FtpFgygALI) size seems to increase every week..

Can you send these files.

**Comment by AGuyNamedJens** [comment]
> > ![image](https://private-user-images.githubusercontent.com/34610614/365453015-876b4e30-0f71-456f-901a-290ddcb5ad81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDA1OTQsIm5iZiI6MTcyNTg0MDI5NCwicGF0aCI6Ii8zNDYxMDYxNC8zNjU0NTMwMTUtODc2YjRlMzAtMGY3MS00NTZmLTkwMWEtMjkwZGRjYjVhZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAwMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZjQwMzU3MzgwZmIzODg0MzY4OWY0YTRmYWFjMjRmY2FlZGU1NmI2NTc5ZDAzMTE1ZDc5YmJiOWU1MmJiZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Q2mMPmrOyL2ri4K0A5blkrcxp-ecb0k-FtpFgygALI) size seems to increase every week..
> 
> Can you send these files.

Yes, i'll link them here since it just happened again https://www.dropbox.com/scl/fo/g1efg3dc84kygfoqluq01/AEL54zKV26dRaVL_471XZxs?rlkey=nforp9f5yqavfvl8rsujed1io&st=xir9z3wi&dl=0:

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/DeathMessages/commit/29d8a8e921e40965287b91eb8c8f9ab20394de00

Please test.
