### ISSUE TITLE
Startup Issue in 1.21

### ISSUE THREAD

**Issue by TheDieselPunk** [Winds-Studio/DeathMessages#85]
I see there's a similar issue but this may be a different issue since Paper 1.21 is remapping the plugin. I also get the same error with v1.4.19.

[14:29:18] [Server thread/INFO]: [DeathMessages] Loading server plugin DeathMessages v1.4.20-SNAPSHOT
[14:29:18] [Server thread/ERROR]: [DeathMessages] Error initializing plugin 'DeathMessages-1.4.20-SNAPSHOT.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.apache.logging.log4j.Logger.error(Object)" because "dev.mrshawn.deathmessages.DeathMessages.LOGGER" is null
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.utils.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:339) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.utils.CommentedConfiguration.loadConfiguration(CommentedConfiguration.java:300) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.config.PlayerDeathMessages.initialize(PlayerDeathMessages.java:63) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.config.ConfigManager.initialize(ConfigManager.java:33) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.DeathMessages.initConfig(DeathMessages.java:138) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at DeathMessages-1.4.20-SNAPSHOT.jar/dev.mrshawn.deathmessages.DeathMessages.onLoad(DeathMessages.java:112) ~[DeathMessages-1.4.20-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-97-e71c1df]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-97-e71c1df]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-97-e71c1df]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-97-e71c1df]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:544) ~[paper-1.21.jar:1.21-97-e71c1df]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-97-e71c1df]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.21.jar:1.21-97-e71c1df]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-97-e71c1df]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Dreeam-qwq** [comment]
Can you try https://github.com/Winds-Studio/DeathMessages/actions/runs/10013140623 ?

**Comment by TheDieselPunk** [comment]
This seems to have fixed it. Tested on that version of paper I was running on (dev) and also on current stable that was just released. Thank you!
